image: node:latest

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build # Assurez-vous que cette commande construit votre projet dans le répertoire public
  artifacts:
    paths:
      - public/
  only:
    - main

pages:
  stage: deploy
  script:
    - cp -r public/ .public/
  artifacts:
    paths:
      - .public
  only:
    - main
